#!/usr/bin/env bash
# ...
file=/var/run/myscript.pid

echo $$ > $file

trap 'echo "I hate the kill command" ; rm -f $file ; exit ' SIGTERM
trap 'echo "Y U no love me?|"' SIGINT
trap 'rm $file ; exit ' SIGQUIT

while true 
do
echo "To infinity and beyond"
sleep 2
done