#!/usr/bin/env bash
# Displays bad luck on the 4th loop interation good luck on the 8th
# loop iteration and Best School for others
i=1
while [ $i -ne 11 ]
do
if [ $i -eq 4 ]
then
echo "bad luck"
elif [ $i -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
((i++))
done
