#!/usr/bin/env bash
# gives information about the school file
filename=school
if [ ! -e $filename ]
then
echo "$filename file does not exist"
else
echo "$filename file exists"
   if [ -f "$filename" ]
   then  
   content="$(cat $filename)"
   elif [ -d "$filename" ]
   then
   content="d"
   fi

   if [ -z "$content" ]
   then
   echo "$filename file is empty"
   else
   echo "$filename file is not empty"
   fi
   if [ -f $filename ]
   then
   echo "$filename is a regular file"
   fi
fi